;==================================================
; string.inc - include file for string.asm
;
; Copyright 2022 by Mark Seminatore
; See LICENSE.md for rights and obligations
;===================================================

;==========================================
; Declare exported functions
;==========================================
EXTERN strlen
EXTERN strcpy
EXTERN islower
EXTERN isupper
EXTERN tolower
EXTERN toupper
EXTERN strupr
